### ISSUE TITLE
Page break does not display properly

### ISSUE THREAD

**Issue by fabianoP** [Maynooth-Center-for-Digital-Humanities/Magellan#1]
The page break is not working properly, it does not separate the transcription in pages.

**Comment by fabianoP** [comment]
The solution is to get rid of the pb in the transcription field because it is in the middle of the transcription while the best practise will be to close the text tag and reopen it.

**Comment by fabianoP** [comment]
The solution will be in the next release, Monday 01/05

**Comment by MonikaBarget** [comment]
Working with people at the Clondalkin Community Centre, I realised that it was confusing for them that the page break in the old EXPLORE was only clear in close-up mode (clicking on one of the letter images on the right), but not in full-letter view. 

Here is one example that shows that the text is displayed as one block if viewed as a whole:

http://letters1916.maynoothuniversity.ie/explore/letters/930

![image](https://user-images.githubusercontent.com/38257338/39576694-f147adfa-4ed6-11e8-82c8-6f109d6497d5.png)


The page break in the detailed view works, but I think it is necessary to mark the page-break in any mode as this makes it easier to jump to the right images.  

Some of our letters are 10 pages long. This has to mirrored when people open the items.

**Comment by fabianoP** [comment]
The feature is implemented, all the XML needs to be uploaded again. @MonikaBarget just schedule with Stavros when it will be happening.
